language: csharp
dotnet: 2.0.0
sudo: false  # use the new container-based Travis infrastructure 


env:
  global:
    - CONFIGURATION="Release"
solution: FsAttoparsec.sln

install:
  - nuget install NUnit.Console -Version 3.7.0 -OutputDirectory packages -ExcludeVersion
  - msbuild /t:restore FsAttoparsec.sln
script:
  - msbuild ./FsAttoparsec.sln /p:Configuration=${CONFIGURATION}
  - mono ./packages/NUnit.ConsoleRunner/tools/nunit3-console.exe ./FsAttoparsec.Tests/bin/${CONFIGURATION}/net452/FsAttoparsec.Tests.dll
  - dotnet test -f netcoreapp2 -c ${CONFIGURATION} FsAttoparsec.Tests/

