branches:
  except:
    - gh-pages
image: Visual Studio 2017
build:
  project: FsAttoparsec.sln
  verbosity: minimal
before_build:
  - msbuild /t:restore src
skip_tags: true

skip_commits:
  message: \[(ci skip|skip ci)\].*

clone_depth: 50

configuration:
  - Release

test_script:
  - dotnet test --configuration Release src/Tests
