branches:
  except:
    - gh-pages
image: Visual Studio 2017
build_script:
  - msbuild /p:Configuration=Release FsAttoparsec.sln
before_build:
  - msbuild /t:restore FsAttoparsec.sln
skip_tags: true

skip_commits:
  message: \[(ci skip|skip ci)\].*

clone_depth: 50

configuration:
  - Release

test_script:
  - dotnet test --configuration Release FsAttoparsec.Tests/
